// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260401195736_AddAvoirAndTypeDocument")]
    partial class AddAvoirAndTypeDocument
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Facture", b =>
                {
                    b.Property<int>("NumeroFacture")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("NumeroFacture"));

                    b.Property<DateTime>("DateFacture")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateLimitePaiement")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateValidation")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("FactureOrigineId")
                        .HasColumnType("int");

                    b.Property<string>("IdSaveEfact")
                        .HasColumnType("longtext");

                    b.Property<string>("IdTTN")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ModeConnexion")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MontantEnLettres")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<decimal>("MontantRemise")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("MontantTTC")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("MontantTimbre")
                        .HasColumnType("decimal(18,3)");

                    b.Property<DateTime?>("PeriodeAu")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("PeriodeDu")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("QrCode")
                        .HasColumnType("longtext");

                    b.Property<decimal>("RemiseGlobale")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("TiersId")
                        .HasColumnType("int");

                    b.Property<bool>("TimbreFiscal")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("TotalHT")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("TotalHTAvantRemise")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("TotalTVA")
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("TypeDocument")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("NumeroFacture");

                    b.HasIndex("FactureOrigineId");

                    b.HasIndex("TiersId");

                    b.ToTable("Factures");
                });

            modelBuilder.Entity("backend.Models.LigneFacture", b =>
                {
                    b.Property<int>("Numligne")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Numligne"));

                    b.Property<string>("Designation")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("MontantHT")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("MontantTTC")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("MontantTVA")
                        .HasColumnType("decimal(18,3)");

                    b.Property<int>("NumeroFacture")
                        .HasColumnType("int");

                    b.Property<decimal>("PrixUnitaire")
                        .HasColumnType("decimal(18,3)");

                    b.Property<int>("ProduitId")
                        .HasColumnType("int");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.Property<decimal>("RemiseLigne")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("TauxTVA")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Numligne");

                    b.HasIndex("NumeroFacture");

                    b.HasIndex("ProduitId");

                    b.ToTable("LigneFactures");
                });

            modelBuilder.Entity("backend.Models.Produit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("PrixUnitaire")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("TauxTVA")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("Produits");
                });

            modelBuilder.Entity("backend.Models.Tiers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("CIN")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("CodeClient")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Contact")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("IdSaveEfact")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("MatriculeFiscal")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Profil")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("SiteWeb")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Telecopie")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Telephone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Tiers");
                });

            modelBuilder.Entity("backend.Models.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("backend.Models.Facture", b =>
                {
                    b.HasOne("backend.Models.Facture", "FactureOrigine")
                        .WithMany()
                        .HasForeignKey("FactureOrigineId");

                    b.HasOne("backend.Models.Tiers", "Tiers")
                        .WithMany("Factures")
                        .HasForeignKey("TiersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FactureOrigine");

                    b.Navigation("Tiers");
                });

            modelBuilder.Entity("backend.Models.LigneFacture", b =>
                {
                    b.HasOne("backend.Models.Facture", "Facture")
                        .WithMany("Lignes")
                        .HasForeignKey("NumeroFacture")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Produit", "Produit")
                        .WithMany()
                        .HasForeignKey("ProduitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Facture");

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("backend.Models.Facture", b =>
                {
                    b.Navigation("Lignes");
                });

            modelBuilder.Entity("backend.Models.Tiers", b =>
                {
                    b.Navigation("Factures");
                });
#pragma warning restore 612, 618
        }
    }
}
